        Throwable origExceptionCaught = exchange.getProperty(Exchange.EXCEPTION_CAUGHT, Throwable.class);
        if (origExceptionCaught != null) {
            log.error("Second Exception occured inside exception handler. Failing exchange", e);
            exchange.setProperty(Exchange.UNIT_OF_WORK_EXHAUSTED, true);
        } else {

            // store the original caused exception in a property, so we can restore it later
            exchange.setProperty(Exchange.EXCEPTION_CAUGHT, e);
        }
